word_count:
	gcc -o word_count word_count.c -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -lglib-2.0

ex_compile:
	gcc -o ex_compile ex_compile.c -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -lglib-2.0
